### ISSUE TITLE
cisco.meraki.devices_cellular_sims - fails due to input parameters.

### ISSUE THREAD

**Issue by benjamincash89** [meraki/dashboard-api-ansible#10]
When applying the cisco.meraki.devices_cellular_sims plugin with the below parameters the error further below is thrown.

- name: Set 4G Interface
  cisco.meraki.devices_cellular_sims:
    meraki_api_key: "{{ api_key }}"
    state: present
    apns:
    - allowedIpTypes:
      - ipv4
     - ipv6
      name: 
    isPrimary: false
    serial: "{{ mx_serial | first }}"
    slot: sim1

Thrown error:

fatal: []: FAILED! => {"changed": false, "msg": ["apns, isPrimary, slot. Supported parameters include: meraki_action_batch_retry_wait_time, meraki_api_key, meraki_base_url, meraki_be_geo_id, meraki_certificate_path, meraki_inherit_logging_config, meraki_log_file_prefix, meraki_log_path, meraki_maximum_retries, meraki_nginx_429_retry_wait_time, meraki_output_log, meraki_print_console, meraki_requests_proxy, meraki_retry_4xx_error, meraki_retry_4xx_error_wait_time, meraki_simulate, meraki_single_request_timeout, meraki_suppress_logging, meraki_use_iterator_for_get_pages, meraki_wait_on_rate_limit, serial, simFailover, sims, state."]}

**Comment by obrigg** [comment]
Thank you for pointing this out. Can you kindly try the following format?
```
    - name: Update Device Cellular Sims
      cisco.meraki.devices_cellular_sims:
        state: present
        sims:
          - slot: sim1
            apns:
            - allowedIpTypes:
              - ipv4
              name: internet
            isPrimary: true
        serial: AAAA-BBBB-CCCC
```
