### ISSUE TITLE
cisco.meraki.devices_cellular_sims does not update SIM details in dashboard

### ISSUE THREAD

**Issue by tfawbs** [meraki/dashboard-api-ansible#113]
When trying to update the SIM details on a cellular MX device in Dashboard with the cisco.meraki.devices_cellular_sims, the result returned is:
> "result": "Object already present"

When testing with the [API](https://developer.cisco.com/meraki/api-v1/update-device-cellular-sims/) itself there is no issue, I get a returned 200 Success and see the details update in Dashboard on the targeted device.

When testing with the Ansible [module](https://docs.ansible.com/ansible/latest/collections/cisco/meraki/devices_cellular_sims_module.html#ansible-collections-cisco-meraki-devices-cellular-sims-module) no changes are made, I get a returned ok=1 and when running with a -vvv I get a result saying the object is already present.

Playbook is as follows:

```
- hosts: localhost
  gather_facts: false
  vars_files:
    - credentials-lab.yml
  tasks:
      - name: Update APN for SIM1 on the target Serial
        cisco.meraki.devices_cellular_sims:
          meraki_api_key: "{{ meraki_api_key }}"
          state: present
          serial: Q2JY-XXXX-XXXX
          simFailover:
            enabled: false
            timeout: null
          simOrdering:
            - sim1
          sims:
            - apns:
                - allowedIpTypes:
                    - ipv4
                  authentication:
                    type: pap
                    username: ansible
                  name: "internet.aust.ansible"
              isPrimary: true
              simOrder: 1
              slot: sim1
```

Response from running this with -vvv

```
TASK [Update APN for SIM1 on the target Serial] ********************************************************************************************
task path: /home/tim/ansible/Set_APN.yaml:11
ok: [localhost] => {
    "changed": false,
    "meraki_response": {
        "apns": [
            {
                "allowedIpTypes": [
                    "ipv4",
                    "ipv6"
                ],
                "authentication": {
                    "type": "none"
                },
                "name": "test"
            }
        ],
        "isPrimary": true,
        "simOrder": 1,
        "slot": "sim1"
    },
    "result": "Object already present"
}
```

I am running cisco.meraki 2.20.5.
Is there a way I can get the module to apply the parameters even if it thinks the object already is present or is this unexpected behaviour?
