### ISSUE TITLE
Python 3.11 error with cisco.meraki ansible collections.

### ISSUE THREAD

**Issue by ribua** [meraki/dashboard-api-ansible#118]
Hi team,

I have tested the cisco modules for **switch_port** that fails when I run it on my Linux Operating system that runs python version 3.11 and returns the below error. 

```
sh-5.1$ ansible-playbook -i hosts playbook.yml  -vvvv
ansible-playbook [core 2.16.14]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.11 (main, Feb 10 2025, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-5)] (/usr/bin/python3.11)
  jinja version = 3.1.6
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from 
host_list declined parsing /tmp/hosts as it did not pass its verify_file() method
script declined parsing /tmp/hosts as it did not pass its verify_file() method
auto declined parsing /tmp/hosts as it did not pass its verify_file() method
Parsed /tmp/hosts inventory source with ini plugin
Loading collection cisco.meraki from /usr/share/ansible/collections/ansible_collections/cisco/meraki
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.11/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yml ***************************************************************************************************************************************************************************************************************************************
Positional arguments: playbook.yml
verbosity: 4
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/tmp/hosts',)
forks: 5
1 plays in playbook.yml

PLAY [localhost] *********************************************************************************************************************************************************************************************************************************************
Loading collection ansible.utils from /usr/share/ansible/collections/ansible_collections/ansible/utils

TASK [Configure Switch1 Port1 To Router] *********************************************************************************************************************************************************************************************************************
task path: /tmp/playbook.yml:12
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 165, in run
    res = self._execute()
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 644, in _execute
    result = self._handler.run(task_vars=vars_copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ansible/collections/ansible_collections/cisco/meraki/plugins/action/devices_switch_ports.py", line 377, in run
    response = obj.update()
               ^^^^^^^^^^^^
  File "/usr/share/ansible/collections/ansible_collections/cisco/meraki/plugins/action/devices_switch_ports.py", line 320, in update
    id_ = prev_obj_name.get("id")
          ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution: 'list' object has no attribute 'get'",
    "stdout": ""
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

Below is the playbook that I am using for this purpose 

```
---
# Notes: 
# This playbook is designed to configure the switch port settings, you can do all or a selected few ports and you 
# can configure additional options if you look up the module details
- hosts: localhost
  gather_facts: false
  vars:
    switch1_serial: XXXXXXXXXXX
    site_abbv: XXX

  tasks:
    - name: Configure Switch1 Port1 To Router
      cisco.meraki.devices_switch_ports:
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch1_serial }}"
        name: Uplink to RW-{{ site_abbv }}-01
        type: trunk
        vlan: 25
        portId: 1
```

The playbook works fine when I run with python version 3.12 . 

Ribu
