### ISSUE TITLE
cisco.meraki.networks_appliance_firewall_l7_firewall_rules does not have rules type Countries 

### ISSUE THREAD

**Issue by loopwert** [meraki/dashboard-api-ansible#12]
Mx for the layer 7 rules has the capability of geo blocking. The older module has this ability but according to the documentation this modules only has Type of the L7 rule. One of ‘application’, ‘applicationCategory’, ‘host’, ‘port’, ‘ipRange’.

**Comment by obrigg** [comment]
L7 rules by country work with the new modules (as long as you have the SD-WAN license, of course).

```
    - name: Create FW L7 rules
      cisco.meraki.networks_appliance_firewall_l7_firewall_rules:
        networkId: "{{network_id}}"
        rules:
       
        - policy: deny
          type: blockedCountries
          value:
            - IT
             
        - policy: deny
          type: allowedCountries
          value:
            - FR
```

We will check the documentation.
