### ISSUE TITLE
Problem with devices_switch_ports module

### ISSUE THREAD

**Issue by dubbsthedestroyer** [meraki/dashboard-api-ansible#34]
This is my task i am having an issue with the Verbose is below

ansible-playbook [core 2.16.0]
python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
cisco.meraki                  2.16.14
meraki                 1.39.0

- name: Turn PoE Off
          cisco.meraki.devices_switch_ports:
            meraki_api_key: "{{ MERAKI_KEY }}"
            state: present
            serial: "{{ ms_serial }}"
            portId: "{{ port number }}"
            vlan: 50
            poeEnabled: false

TASK [Turn PoE Off] *********************************************************************************************************************************************************************************
task path: /home/dubbs/meraki-ansible/cycle_poe.yml:26
meraki_compare_equality Access Control None
meraki_compare_equality [] None
meraki_compare_equality True None
meraki_compare_equality True False
The full traceback is:
Traceback (most recent call last):
  File "/home/dubbs/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 165, in run
    res = self._execute()
  File "/home/dubbs/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 641, in _execute
    result = self._handler.run(task_vars=vars_copy)
  File "/home/dubbs/.ansible/collections/ansible_collections/cisco/meraki/plugins/action/devices_switch_ports.py", line 366, in run
    response = obj.update()
  File "/home/dubbs/.ansible/collections/ansible_collections/cisco/meraki/plugins/action/devices_switch_ports.py", line 309, in update
    id_ = prev_obj_name.get("id")
AttributeError: 'list' object has no attribute 'get'
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution: 'list' object has no attribute 'get'",
    "stdout": ""
}

**Comment by dubbsthedestroyer** [comment]
I was able to get a different module to work:

tasks:
    - delegate_to: localhost
      block:
        - name: Query one switchport
          cisco.meraki.devices_switch_ports_info:
            meraki_api_key: '{{ MERAKI_KEY }}'
            serial: "{{ ms_serial }} "
            portId: "{{ port number }}"
          register: query_one
 
        - name: Debug query
          ansible.builtin.debug:
            msg: '{{ query_one }}'

**Comment by obrigg** [comment]
Hello,
Can you kindly try to run the following in verbose mode?

```
    - name: Turn PoE Off
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ MERAKI_KEY }}"
        meraki_suppress_logging: false
        serial: "{{ ms_serial }}"
        portId: "{{ port number }}"
        vlan: 50
        state: present
        poeEnabled: false
```
