### ISSUE TITLE
Unable to create Syslog Server Object

### ISSUE THREAD

**Issue by scoop263** [meraki/dashboard-api-ansible#92]
I have been using this ansible play for some time now, and it seems to have broken.
I have checked the change logs to my best ability but can not see if this feature was deprectated at the dashboard api level or ansible level.

I use the ansible playbooks to create networks from scratch and I am unable to use the cisco.meraki.networks_syslog_servers module to create syslog server objects in a network.

Here is my current playbook
I have also edited the playbook that matches the syntax provided in the anisble community documentation pages, with no resolution.

```
- name: Enable Syslog
  cisco.meraki.networks_syslog_servers:
    meraki_api_key: "{{meraki_api_key}}"
    state: present
    networkId: "{{ meraki_Response.meraki_response.id }}"
    servers:
    - host: 10.52.1.10
      port: 1516
      roles:
        - Flows
    - host: 10.52.1.10
      port: 1517
      roles:
        - URLs
    - host: 10.52.1.10
      port: 1519
      roles:
        - Security events
``` 

The error I am receiving is:

```
The full traceback is:
NoneType: None
fatal: [XXXX.meraki.com]: FAILED! => {
    "changed": false,
    "msg": "Object does not exists, plugin only has update"
}
``` 

Environment:
Cisco.meraki: 2.20.6
Meraki SDK: 1.54.0

**Comment by obrigg** [comment]
@fmunozmiranda, I can reproduce this with:
```
---

- hosts: localhost
  gather_facts: false
  vars:
    networkId: "L_828099381482771185"
  tasks:

  - name: Syslog servers
    cisco.meraki.networks_syslog_servers:
      networkId: "{{ networkId }}"
      servers:
      - host: 1.2.3.4
        port: 443
        roles:
        - Wireless event log
        - URLs
      state: present
```
